# thanks to https://github.com/travis-ci/travis-ci/issues/5775
sudo: false

language: r
r:
  - oldrel
  - release
  - devel

cache: packages

before_install:
  - cd pkg
  
install:
  - Rscript -e 'install.packages(c("devtools", "roxygen2", "testthat", "knitr", "rmarkdown"))'
  - Rscript -e 'devtools::install_deps(); install.packages("covr")'
script:
  - Rscript -e 'devtools::check()'
  
notifications:
  email:
    on_success: change
    on_failure: change

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::coveralls()'
