# thanks to https://github.com/travis-ci/travis-ci/issues/5775
sudo: false

language: r
r:
  - oldrel
  - release
  - devel

cache: packages

before_install:
  - cd pkg

install:
  - Rscript -e 'install.packages(c("devtools", "covr"))'
  - Rscript -e 'devtools::install_deps(dependencies = TRUE, threads = 2)'
script:
  - Rscript -e 'devtools::check()'

notifications:
  email:
    on_success: change
    on_failure: change

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::coveralls()'
