# thanks to https://github.com/travis-ci/travis-ci/issues/5775
sudo: false

addons:
  apt:
    packages:
      - libxml2-dev libgit2-dev

language: r
r:
  - oldrel
  - release
  - devel

cache: packages

before_install:
  - cd pkg

install:
  - Rscript -e 'install.packages(c("devtools", "covr"), repos = "https://cloud.r-project.org")'
  - Rscript -e 'devtools::install_deps(dependencies = TRUE, threads = 2, repos = "https://cloud.r-project.org")'

script:
  - Rscript -e 'devtools::check()'
  - Rscript -e 'devtools::test()'

after_success:
  - Rscript -e 'covr::coveralls()'
